config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations"}
  resources :blogtexts do
    resources :comments do
      resources :replies
    end
  end
  resources :blogs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :home
  root 'home#index'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/blogtext.rb
class Blogtext < ApplicationRecord

  has_rich_text :blogpost
  has_many :comments, dependent: :destroy


end

app/controllers/blogtexts_controller.rb
class BlogtextsController < ApplicationController
  before_action :set_blogtext, only: %i[ show edit update destroy ]

  # GET /blogtexts or /blogtexts.json
  def index
    @blogtexts = Blogtext.all.sort_by{|x| x[:created_at]}.reverse!
  end

  # GET /blogtexts/1 or /blogtexts/1.json
  def show
    @comments = Comment.where("blogtext_id = ?", params[:id]).sort_by{|x| x[:created_at]}.reverse!
    @comment = Comment.new
  end

  # GET /blogtexts/new
  def new
    @blogtext = Blogtext.new
  end

  # GET /blogtexts/1/edit
  def edit
  end


  # POST /blogtexts or /blogtexts.json
  def create
    @blogtext = Blogtext.new(blogtext_params)

    respond_to do |format|
      if @blogtext.save
        format.html { redirect_to blogtext_url(@blogtext), notice: "Blogtext was successfully created." }
        format.json { render :show, status: :created, location: @blogtext }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blogtext.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogtexts/1 or /blogtexts/1.json
  def update
    respond_to do |format|
      if @blogtext.update(blogtext_params)
        format.html { redirect_to blogtext_url(@blogtext), notice: "Blogtext was successfully updated." }
        format.json { render :show, status: :ok, location: @blogtext }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blogtext.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogtexts/1 or /blogtexts/1.json
  def destroy
    @blogtext.destroy!

    respond_to do |format|
      format.html { redirect_to blogtexts_url, notice: "Blogtext was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def my_blog
    @blogtexts = Blogtext.where("user_id = ?", current_user.id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blogtext
      @blogtext = Blogtext.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blogtext_params
      params.require(:blogtext).permit(:owner, :title, :blogpost, :user_id)
    end
end

app/helpers/blogtexts_helper.rb
module BlogtextsHelper
end

app/views/blogtexts/_blogtext.html.erb
<div id="<%= dom_id blogtext %>">
  <p>


    <h2><%= blogtext.title %> By <%= link_to blogtext.owner, blog_path(id: blogtext.user_id), style: "color:#c0c0c0" %></h2>

    <div style="border-radius: 15px; border-style: solid; border-color: #2E2F30; background: #aaaaaa; color: #555555">
      <%= blogtext.blogpost %>

    </div>
  </p>

</div>

app/views/blogtexts/_form.html.erb
<%= form_with(model: @blogtext) do |form| %>
  <% if @blogtext.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@blogtext.errors.count, "error") %> prohibited this blogtext from being saved:</h2>

      <ul>
        <% @blogtext.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.hidden_field :owner, value: current_user.name %>
  </div>

  <div>
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div>
    <%= form.label "blogs Title" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label "New blogs" %>
    <%= form.rich_text_area :blogpost %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blogtexts/edit.html.erb
<h1>Editing blogtext</h1>

<%= render "form", blogtext: @blogtext %>

<br>

<div>
  <%= link_to "Show this blogtext", @blogtext %> |
  <%= link_to "Back to blogtexts", blogtexts_path %>
</div>

app/views/blogtexts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Blogs</h1>

<%= link_to "My Blogs", blogs_path, class: "btn btn-secondary" %>
<%= link_to "Create new Blog", new_blogtext_path, class: "btn btn-secondary" %>
<div id="blogtexts" style="display: flex; flex-wrap: wrap">
  <% @blogtexts.each do |blogtext| %>
    <div style="display: flex; margin-bottom: 15px; background: #555555; border-radius: 15px; margin-right: 15px">
      <%= image_tag(User.find(blogtext.user_id).header_picture, style: "border-radius: 50%") %>
      <div style="width: 250px; height: 110px">
        <div><%= blogtext.owner %></div>
        <%= link_to blogtext.title, blogtext, class: "btn btn-secondary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/blogtexts/new.html.erb
<%= render "form", reply: @reply %>

<br>

<div>
  <%= link_to "Back to Blog", blogtexts_path %>
</div>

app/views/blogtexts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @blogtext %>
<div style="display: block; color: #555555">
  <div><%= link_to "Back to Blogs", blogtexts_path, class:"btn btn-secondary" %>
  </div>

  <% if @blogtext.user_id == current_user.id %>
    <%= link_to "Edit Blog", edit_blogtext_path(@blogtext), class: "btn btn-secondary"%>
    <%= button_to "Destroy Blog", @blogtext, method: :delete, class: "btn btn-secondary" %>
  <% end %>

  <h2>Comments</h2>
  <%= form_with(url:  @blogtext.id.to_s  + "/comments", model: @comment ) do |f| %>
    <div class="field">
      <%= f.text_area :comment, class: "form-control", style: "background: #555555" %>
    </div>
    <%= f.text_field :username, value: current_user.name, type: "hidden" %>
    <%= f.text_field :user_id, value: current_user.id, type: "hidden" %>
    <%= f.text_field :blog_id, value: @blogtext.id, type: "hidden" %>
    <div>
      <%= f.submit "Add Comment", class: "btn btn-secondary", style: " background: #555555" %>
    </div>
  <% end %>


    <% @comments.each do |comment| %>
    <div class="comment" id="comment_<%= comment.id %>" style="display: block; background: #aaaaaa; border-radius: 15px; margin-bottom: 5px">
        <div style="display: flex;">
          <div><%= image_tag(User.find(comment.user_id).comment_picture, style: "border-radius: 50%") %></div>
          <div style="display: block">
            <div><%= comment.username + " " + comment.time %></div>
            <div><%= comment.comment %></div>
          </div>
          <%= button_to "reply", new_blogtext_comment_reply_path(@blogtext.id, comment.id), class: "btn btn-secondary", method: :get %>
          <% if @blogtext.user_id == current_user.id %>
            <%= button_to "delete", blogtext_comment_path(@blogtext.id, comment.id),  method: :delete, class: "btn btn-secondary" %>
          <% end %>
        </div>
        <div>
          <% if Reply.where("comment_id = ?", comment.id).length == 1 %>
            <button class="toggleReplies" data-comment-id="<%= comment.id %>" data-replies-count="<%= Reply.where("comment_id = ?", comment.id).length%>" style="background: #555555; border-radius: 5%">View reply</button>
            <div id="reply_<%=comment.id %>" class="reply hidden">
              <h3>Replies</h3>
              <% replies = Reply.where("comment_id = ?", comment.id) %>
              <% replies.each do |text| %>
                <div><%= image_tag(User.find(text.user_id).comment_picture, style: "border-radius: 50%") %></div>
                <div style="display: block">
                  <div><%= text.username + " " + text.time %></div>
                  <div><%= text.reply %></div>
                </div>
                <% if text.user_id == current_user.id %>
                  <%= button_to "delete reply", blogtext_comment_reply_path(@blogtext.id, comment.id, text.id), method: :delete  %>
                <% end %>
              <% end %>
            </div>
          <% elsif Reply.where("comment_id = ?", comment.id).length > 1%>
            <button class="toggleReplies" data-comment-id="<%= comment.id %>" data-replies-count="<%= Reply.where("comment_id = ?", comment.id).length %>" style="background: #555555; border-radius: 5%">View <%= Reply.where("comment_id = ?", comment.id).length %> replies</button>
            <div id="reply_<%=comment.id %>" class="reply hidden">
              <h3>Replies</h3>
              <% replies = Reply.where("comment_id = ?", comment.id) %>
              <% replies.each do |text| %>
                <div><%= image_tag(User.find(text.user_id).comment_picture, style: "border-radius: 50%") %></div>
                <div style="display: block">
                  <div><%= text.username + " " + text.time %></div>
                  <div><%= text.reply %></div>
                </div>
                <% if text.user_id == current_user.id %>
                  <%= button_to "delete reply", blogtext_comment_reply_path(@blogtext.id, comment.id, text.id), method: :delete, class: "btn btn-secondary"  %>
                <% end %>
              <% end %>
            </div>
          <% end %>
        </div>
    </div>
    <% end %>


</div>