config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations"}
  resources :blogtexts do
    resources :comments do
      resources :replies
    end
  end
  resources :blogs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :home
  root 'home#index'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :comment, optional: true

  def time
    created_at.strftime("at %l:%M %p (%m/%d/%y)")
  end
end

app/controllers/replies_controller.rb
# frozen_string_literal: true

class RepliesController < ApplicationController

  def index

  end

  def new
    @reply = Reply.new
    @comment_id = params[:comment_id]
  end
  def create
    @reply = Reply.new(reply_params)
    respond_to do |format|
      if @reply.save
        format.html { redirect_to blogtext_path(params[:blogtext_id]), notice: "Reply was successfully created." }
        format.json { render :show, status: :created, location: Blogtext.find(params[:blogtext_id]) }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @reply = Reply.find(params[:id])
    @reply.destroy!
    redirect_to blogtext_path(params[:blogtext_id]), notice: "Reply was successfully deleted"
  end

  private
  def reply_params
    params.require(:reply).permit(:username, :reply, :comment_id, :user_id)
  end
end

app/views/replies/_form.html.erb
<%= form_with(url: blogtext_comment_replies_path, model: @reply) do |form| %>
  <% if @reply.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(reply.errors.count, "error") %> prohibited this reply from being saved:</h2>

      <ul>
        <% @reply.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.hidden_field :username, value: current_user.name %>
  </div>

  <div>
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div>
    <%= form.hidden_field :comment_id, value: @comment_id %>
  </div>

  <div>
    <%= form.label "reply" %>
    <%= form.text_field :reply %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/replies/new.html.erb
<h1>Add a reply to <%= Comment.find(@comment_id).username %>'s Comment </h1>

<%= render "form", blogtext: @reply %>

<br>

<div>
  <%= link_to "Back to blogtexts", blogtext_path(Comment.find(@comment_id).blog_id) %>
</div>